[package]
name = "minecraft-prometheus-exporter"
version = "1.1.0"
edition = "2018"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
license = "MPL-2.0"
description = "A prometheus exporter for minecraft servers"
repository = "https://github.com/Sciencentistguy/minecraft-prometheus-exporter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better-panic = "0.2.0"
clap = "2.34.0"
eyre = "0.6.5"
once_cell = "1.8.0"
prometheus = "0.13.0"
rcon = "0.5.2"
regex = "1.5.4"
reqwest = { version = "0.11.7", features = ["json"] }
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.73"
serde_yaml = "0.8.23"
structopt = "0.3.25"
tokio = { version = "1.14.0", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
walkdir = "2.3.2"
warp = "0.3.2"
