[package]
name = "minecraft-prometheus-exporter"
version = "1.1.0"
edition = "2018"
authors = ["Jamie Quigley <jamie@quigley.xyz>"]
license = "MPL-2.0"
description = "A prometheus exporter for minecraft servers"
repository = "https://github.com/Sciencentistguy/minecraft-prometheus-exporter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better-panic = "0.2.0"
clap = "2.33.3"
eyre = "0.6.5"
once_cell = "1.8.0"
prometheus = "0.12.0"
rcon = "0.5.2"
regex = "1.5.4"
reqwest = { version = "0.11.4", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
serde_yaml = "0.8.21"
structopt = "0.3.23"
tokio = { version = "1.11.0", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
walkdir = "2.3.2"
warp = "0.3.1"
